int _putchar(char C);
void print_alphabet(void);
void print_alphabet_std(void);
int _islower(int c);
int _isalpha(int c);
int print_sign(int n);
int _ads(int);
int print_last_digit(int);
void jack_bauer(void);
void time_table(void);
int ads(int, int);
void print_to_get(int n);
void print_timers_table(int n);
